checking git diff with different predefined vars

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -10,18 +10,19 @@ check-changelog:
     - merge_requests
   script:
     - echo "===== Begin Changelog Check ====="
-    - echo "Source branch - $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME"
-    - echo "Target branch - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
-    - git branch -a
-    - git diff --name-only refs/remotes/origin/$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME refs/remotes/origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME
-    - git diff --name-only "$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME" "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
-    - CHANGES=$(git diff --name-only "$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME" "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" | grep '^CHANGELOG.md$')
-    - if [ -n "$CHANGES" ]; then
-        echo "===== Changelog has been updated! =====";
-      else
-        echo "ERROR Changelog not updated";
-        exit 1;
-      fi
+    - echo "Target branch - $CI_COMMIT_REF_NAME"
+    - echo "Latest commit on source branch - $CI_COMMIT_SHA"
+    - git diff --name-only $CI_COMMIT_REF_NAME $CI_COMMIT_SHA
+    # - git branch -a
+    # - git diff --name-only refs/remotes/origin/$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME refs/remotes/origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME
+    # - git diff --name-only "$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME" "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
+    # - CHANGES=$(git diff --name-only "$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME" "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" | grep '^CHANGELOG.md$')
+    # - if [ -n "$CHANGES" ]; then
+    #     echo "===== Changelog has been updated! =====";
+    #   else
+    #     echo "ERROR Changelog not updated";
+    #     exit 1;
+    #   fi
 
 # trigger_tests:
 #   stage: run-test-suite
