first attempt at linking release and test repos

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,59 +1,30 @@
-variables:
-  ALLOC_NAME: "deepopt_gitlab_runner_build_test_alloc_${CI_PIPELINE_ID}"
-
 stages:
-  - allocate
-  - changelog
-  - test-unit
-  # - test-integration
-  # - deploy
-  - deallocate
+  - check-changelog
+  - run-test-suite
 
-allocate_nodes:
+check-changelog:
   tags:
     - shell
-    - quartz
-  stage: allocate
+  stage: check-changelog
+  only:
+    - merge_requests
   script:
-    - echo "===== begin alloc for remaining stages ====="
-    -  salloc -N 1 --exclusive -p pdebug -t 60 --no-shell --job-name=$ALLOC_NAME
-    - JOBID=$(squeue -h --name=${ALLOC_NAME} --format=%A)
-    - echo "===== alloc'd JOBID $JOBID ====="
+    - echo "===== Begin Changelog Check ====="
+    - CHANGES=$(git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA | grep '^CHANGELOG.md$')
+    - if [ -n "$CHANGES" ]; then
+        echo "===== Changelog has been updated! =====";
+      else
+        echo "ERROR Changelog not updated";
+        exit 1;
+      fi
 
-deallocate_nodes:
-  tags:
-    - shell
-    - quartz
-  stage: deallocate
-  when: always
-  script:
-    - export JOBID=$(squeue -h --name=${ALLOC_NAME} --format=%A)
-    - ([[ -n "${JOBID}" ]] && scancel ${JOBID} || echo "Job ${JOBID} not running")
+trigger_tests:
+  stage: run-test-suite
+  trigger:
+    project: kur1/deepopt_tests
 
-.changelog:
-  tags:
-    - shell
-    - quartz
-  stage: changelog
-  script:
-    - echo "===== begin changelog ====="
-    - pwd
-
-.test-unit:
-  tags:
-    - shell
-  script:
-    - echo "===== begin test-unit ====="
-    - pwd
-    - which python3
-    - python3 --version
-
-test-unit-3.8:
-  extends: .test-unit
-  stage: test-unit
-  image: python:3.8
-
-test-unit-3.9:
-  extends: .test-unit
-  stage: test-unit
-  image: python:3.9
+# trigger_tests:
+#   script:
+#     - curl -X POST -F token=$CI_JOB_TOKEN -F ref=main https://gitlab.com/api/v4/projects/7151/trigger/pipeline
+#   rules:
+#     - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
